#pragma once

#define SSEQ_CMD_TRACKALLOC 0xFE
#define SSEQ_CMD_TRACKCONF 0x93

#define SSEQ_CMD_REST 0x80
#define SSEQ_CMD_PATCH 0x81
#define SSEQ_CMD_PAN 0xC0
#define SSEQ_CMD_VOL 0xC1
#define SSEQ_CMD_MASTERVOL 0xC2
#define SSEQ_CMD_PRIO 0xC6
#define SSEQ_CMD_NOTEWAIT 0xC7
#define SSEQ_CMD_TIE 0xC8
#define SSEQ_CMD_EXPR 0xD5
#define SSEQ_CMD_TEMPO 0xE1
#define SSEQ_CMD_END 0xFF

#define SSEQ_CMD_GOTO 0x94
#define SSEQ_CMD_CALL 0x95
#define SSEQ_CMD_RET 0xFD
#define SSEQ_CMD_LOOPSTART 0xD4
#define SSEQ_CMD_LOOPEND 0xFC

#define SSEQ_CMD_TRANSPOSE 0xC3
#define SSEQ_CMD_PITCHBEND 0xC4
#define SSEQ_CMD_PITCHBENDRANGE 0xC5

#define SSEQ_CMD_ATTACK 0xD0
#define SSEQ_CMD_DECAY 0xD1
#define SSEQ_CMD_SUSTAIN 0xD2
#define SSEQ_CMD_RELEASE 0xD3

#define SSEQ_CMD_PORTAKEY 0xC9
#define SSEQ_CMD_PORTAFLAG 0xCE
#define SSEQ_CMD_PORTATIME 0xCF
#define SSEQ_CMD_SWEEPPITCH 0xE3

#define SSEQ_CMD_MODDEPTH 0xCA
#define SSEQ_CMD_MODSPEED 0xCB
#define SSEQ_CMD_MODTYPE 0xCC
#define SSEQ_CMD_MODRANGE 0xCD
#define SSEQ_CMD_MODDELAY 0xE0

#define SSEQ_CMD_RANDOM 0xA0
#define SSEQ_CMD_VAR 0xA1
#define SSEQ_CMD_IF 0xA2

#define SSEQ_CMD_PRINTVAR 0xD6

#define SSEQ_CMD_UNSUP2_LO 0xB0
#define SSEQ_CMD_UNSUP2_HI 0xBD
